-- Lisää DROP TABLE lauseet tähän tiedostoon

DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Ryhma CASCADE;
DROP TABLE IF EXISTS Kirjoittaja CASCADE;
DROP TABLE IF EXISTS Lukija CASCADE;
DROP TABLE IF EXISTS Aihe CASCADE;
DROP TABLE IF EXISTS Viesti CASCADE;
DROP TABLE IF EXISTS Keskustelu CASCADE;
